### ISSUE TITLE
Can't use outside Falcon BMS folder

### ISSUE THREAD

**Issue by orffen** [loitho/acmi-compiler#1]
acmi-compiler doesn't work if a custom location is set in `falcon bms.cfg` using `set g_sAcmiDirectory`

Is it possible to allow acmi-compiler not to care about the folder? Maybe as a command-line switch?

**Comment by loitho** [comment]
Hi there,
Sure, that's not a use case I anticipated, I just check if the folder contains ACMI, I'll remove the check and add a message to tell people to check if it's normal.
